# Generated by Django 5.2.4 on 2025-07-31 13:29

import mdeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок страницы для поисковых систем.",
                        max_length=255,
                        verbose_name="SEO Заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание страницы для поисковых систем.",
                        verbose_name="SEO Описание",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        max_length=255, verbose_name="Главный заголовок (Hero)"
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(verbose_name="Подзаголовок (Hero)"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="main_page/",
                        verbose_name="Изображение (Hero)",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок 'О нас'"
                    ),
                ),
                (
                    "about_text",
                    mdeditor.fields.MDTextField(
                        verbose_name="Текст 'О нас'"
                    ),
                ),
                (
                    "higlight_1",
                    models.CharField(
                        max_length=255, verbose_name="Хайлайт блока 'О нас' №1"
                    ),
                ),
                (
                    "higlight_2",
                    models.CharField(
                        max_length=255, verbose_name="Хайлайт блока 'О нас' №2"
                    ),
                ),
                (
                    "services_section_title",
                    models.CharField(
                        default="/наши услуги",
                        max_length=255,
                        verbose_name="Заголовок секции 'Наши услуги'",
                    ),
                ),
                (
                    "lab_title",
                    models.CharField(
                        default="/лаборатория стартапов",
                        max_length=255,
                        verbose_name="Заголовок 'Лаборатория стартапов'",
                    ),
                ),
                (
                    "lab_description",
                    mdeditor.fields.MDTextField(
                        verbose_name="Краткое описание 'Лаборатории'"
                    ),
                ),
                (
                    "dig_title",
                    models.CharField(
                        default="/digital маркетинг",
                        max_length=255,
                        verbose_name="Заголовок 'digital маркетинг'",
                    ),
                ),
                (
                    "dig_description",
                    mdeditor.fields.MDTextField(
                        verbose_name="Краткое описание 'digital маркетинг'"
                    ),
                ),
                (
                    "tokenization_title",
                    models.CharField(
                        default="/токенизация активов и цфа",
                        max_length=255,
                        verbose_name="Заголовок 'Токенизация'",
                    ),
                ),
                (
                    "tokenization_description",
                    mdeditor.fields.MDTextField(
                        verbose_name="Описание 'Токенизация'"
                    ),
                ),
                (
                    "tokenization_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на видео, например, с YouTube или Vimeo.",
                        verbose_name="URL видео 'Токенизация'",
                    ),
                ),
                (
                    "tokenization_links",
                    mdeditor.fields.MDTextField(
                        verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "partners_section_title",
                    models.CharField(
                        default="/партнеры",
                        max_length=255,
                        verbose_name="Заголовок секции 'Партнеры'",
                    ),
                ),
                (
                    "order_section_title",
                    models.CharField(
                        default="/заказать проект",
                        max_length=255,
                        verbose_name="Заголовок секции 'Заказать проект'",
                    ),
                ),
                (
                    "contacts_title",
                    models.CharField(
                        default="/контакты",
                        max_length=255,
                        verbose_name="Заголовок 'Контакты'",
                    ),
                ),
                (
                    "contact_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Телефон"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент главной страницы",
                "verbose_name_plural": "Контент главной страницы",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название партнёра",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Сайт партнёра"),
                ),
            ],
            options={
                "verbose_name": "Партнёр",
                "verbose_name_plural": "Партнёры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "company",
                    models.CharField(
                        max_length=255, verbose_name="Название компании"
                    ),
                ),
                (
                    "project_details",
                    models.TextField(verbose_name="Детали проекта"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email"),
                ),
                (
                    "agreed_to_terms",
                    models.BooleanField(
                        default=False, verbose_name="Согласие с условиями"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на проект",
                "verbose_name_plural": "Заявки на проект",
            },
        ),
        migrations.CreateModel(
            name="ServicePostscriptum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "info",
                    models.TextField(
                        max_length=1000, verbose_name="Информация"
                    ),
                ),
                (
                    "item1",
                    models.CharField(max_length=255, verbose_name="Элемент 1"),
                ),
                (
                    "item2",
                    models.CharField(max_length=255, verbose_name="Элемент 2"),
                ),
                (
                    "item3",
                    models.CharField(max_length=255, verbose_name="Элемент 3"),
                ),
                (
                    "item4",
                    models.CharField(max_length=255, verbose_name="Элемент 4"),
                ),
            ],
            options={
                "verbose_name": "Постскриптум услуги",
                "verbose_name_plural": "Постскриптумы услуг",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название тега"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название технологии"
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Порядковый номер технологии"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="technologies/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "primary_info",
                    models.TextField(
                        max_length=2000, verbose_name="Основная информация"
                    ),
                ),
                (
                    "secondary_info",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Дополнительная информация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Технология",
                "verbose_name_plural": "Технологии",
                "ordering": ["number"],
                "default_related_name": "technology",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(verbose_name="Описание"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название услуги"
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        verbose_name="№ п/п в списке услуг"
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        max_length=1000, verbose_name="Информация об услуге"
                    ),
                ),
                (
                    "content",
                    mdeditor.fields.MDTextField(
                        blank=True, null=True, verbose_name="Содержание услуги"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="services",
                        to="api.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название проекта"
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        max_length=1000, verbose_name="Информация о проекте"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_studies",
                        to="api.service",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="case_studies",
                        to="api.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реальный проект",
                "verbose_name_plural": "Реальные проекты",
                "ordering": ["service", "name"],
            },
        ),
    ]
