# Generated by Django 5.2.4 on 2025-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название технологии')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер технологии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='technologies', verbose_name='Изображение')),
                ('primary_info', models.TextField(max_length=2000, verbose_name='Основная информация')),
                ('secondary_info', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['number'],
                'default_related_name': ('technology',),
            },
        ),
    ]
