# Generated by Django 5.2.4 on 2025-07-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название партнёра')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт партнёра')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ('name',),
            },
        ),
    ]
