# Generated by Django 5.2.4 on 2025-07-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="homepage",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="api.homepagecontent",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="homepage",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="api.homepagecontent",
            ),
        ),
    ]
