# Generated by Django 5.2.4 on 2025-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_partner_homepage_alter_service_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="partners/",
                verbose_name="Логотип",
            ),
        ),
    ]
