# Generated by Django 5.2.4 on 2025-07-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_partner_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepagecontent",
            old_name="higlight_1",
            new_name="highlight_1",
        ),
        migrations.RenameField(
            model_name="homepagecontent",
            old_name="higlight_2",
            new_name="highlight_2",
        ),
    ]
