# Generated by Django 5.2.4 on 2025-08-04 08:19

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Service = apps.get_model('api', 'Service')
    for service in Service.objects.all():
        service.slug = slugify(service.name)
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_higlight_1_homepagecontent_highlight_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(populate_slugs),
    ]
