# Generated by Django 5.2.4 on 2025-08-06 17:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_higlight_1_homepagecontent_highlight_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок карточки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="main_page/",
                        verbose_name="Изображение карточки",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание карточки"),
                ),
            ],
            options={
                "verbose_name": "Карточка лаборатории стартапов",
                "verbose_name_plural": "Карточки лаборатории стартапов",
            },
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="lab_description_ps",
            field=ckeditor.fields.RichTextField(
                default="Постскриптум 'Лаборатория стартапов'",
                verbose_name="Постскриптум 'Лаборатории'",
            ),
        ),
    ]
