# Generated by Django 5.2.4 on 2025-08-06 05:19

from django.db import migrations, models


def generate_slugs(apps, schema_editor):
    Service = apps.get_model('api', 'Service')
    for obj in Service.objects.all():
        if not obj.slug:
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_higlight_1_homepagecontent_highlight_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.RunPython(generate_slugs),
    ]
