# Generated by Django 5.2.4 on 2025-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_labcart_homepagecontent_lab_description_ps_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Адрес"),
                ),
                (
                    "requisites",
                    models.TextField(blank=True, verbose_name="Реквизиты"),
                ),
            ],
            options={
                "verbose_name": "Статика сайта",
                "verbose_name_plural": "Статика сайта",
            },
        ),
    ]
