# Generated by Django 5.2.4 on 2025-08-16 10:15
from mdeditor.fields import MDTextField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок"),
                ),
                (
                    "text",
                    MDTextField(
                        max_length=1000, verbose_name="Основная информация"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юридическая страница",
                "verbose_name_plural": "Юридические страница",
                "ordering": ["slug"],
                "default_related_name": "policy",
            },
        ),
    ]