# Generated by Django 5.2.4 on 2025-08-20 13:14

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_policy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={
                "default_related_name": "policy",
                "ordering": ["slug"],
                "verbose_name": "Юридическая страница",
                "verbose_name_plural": "Юридические страницы",
            },
        ),
        migrations.AlterField(
            model_name="policy",
            name="text",
            field=mdeditor.fields.MDTextField(
                verbose_name="Основная информация"
            ),
        ),
    ]
