# Generated by Django 5.2.4 on 2025-08-20 14:43

from django.db import migrations, models


def copy_name_to_name_running_line(apps, schema_editor):
    Service = apps.get_model('api', 'Service')
    for service in Service.objects.all():
        service.name_running_line = service.name
        service.save(update_fields=['name_running_line'])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_policy_options_alter_policy_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="services_running_line",
            field=models.ManyToManyField(
                blank=True,
                to="api.service",
                verbose_name="Список услуг для бегущей строки",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_running_line",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Наименования для бегущей строки",
            ),        
        ),
        migrations.RunPython(copy_name_to_name_running_line),
    ]
