# Generated by Django 5.2.4 on 2025-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_homepagecontent_services_running_line_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagecontent",
            name="services_running_line",
        ),
        migrations.AddField(
            model_name="service",
            name="in_running_line",
            field=models.BooleanField(
                default=True, verbose_name="Наличие услуги на бегущей строке"
            ),
        ),
    ]
