# Generated by Django 5.2.4 on 2025-08-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_about_fields_in_home_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labcart",
            options={
                "verbose_name": "Стартап или Digital маркетинг",
                "verbose_name_plural": "Карточки лаборатории стартапов и digital маркетинга",
            },
        ),
        migrations.AddField(
            model_name="labcart",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("startup", "Лаборатория стартапов"),
                    ("digital", "Digital маркетинг"),
                ],
                default="startup",
                max_length=25,
                verbose_name="Тип карточки",
            ),
        ),
    ]
