# Generated by Django 5.2.4 on 2025-08-25 16:45

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_homepagecontent_services_running_line_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labcart",
            options={
                "verbose_name": "Стартап или Digital маркетинг",
                "verbose_name_plural": "Карточки лаборатории стартапов и digital маркетинга",
            },
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="about_text",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="contact_address",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="highlight_1",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="highlight_2",
        ),
        migrations.RemoveField(
            model_name="service",
            name="info",
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_highlight_1",
            field=models.CharField(
                default="5+ лет",
                max_length=255,
                verbose_name="Хайлайт блока 'О нас' №1",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_highlight_2",
            field=models.CharField(
                default="100%",
                max_length=255,
                verbose_name="Хайлайт блока 'О нас' №2",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_highlight_subtext",
            field=mdeditor.fields.MDTextField(
                blank=True, verbose_name="Текст под хайлайтами"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_highlight_text_1",
            field=mdeditor.fields.MDTextField(
                blank=True, verbose_name="Текст в хайлайте №1"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_highlight_text_2",
            field=mdeditor.fields.MDTextField(
                blank=True, verbose_name="Текст в хайлайте №2"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_subtitle",
            field=mdeditor.fields.MDTextField(
                blank=True, max_length=255, verbose_name="Подзаголовок 'О нас'"
            ),
        ),
        migrations.AddField(
            model_name="labcart",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("startup", "Лаборатория стартапов"),
                    ("digital", "Digital маркетинг"),
                ],
                default="startup",
                max_length=25,
                verbose_name="Тип карточки",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="about_title",
            field=mdeditor.fields.MDTextField(
                blank=True, max_length=255, verbose_name="Заголовок 'О нас'"
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="hero_title",
            field=mdeditor.fields.MDTextField(
                max_length=255, verbose_name="Главный заголовок (Hero)"
            ),
        ),
    ]
