# Generated by Django 5.2.4 on 2025-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_homepage_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrequest",
            name="project_details",
            field=models.TextField(
                max_length=255, verbose_name="Детали проекта"
            ),
        ),
    ]
