# Generated by Django 5.2.4 on 2025-08-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_projectrequest_project_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="info",
            field=models.TextField(
                default="Краткое описание услуги.",
                max_length=1000,
                verbose_name="Информация об услуге",
            ),
        ),
    ]
