FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.celery.sh /app/entrypoint.celery.sh
RUN chmod +x /app/entrypoint.celery.sh

COPY . .

ENTRYPOINT ["/app/entrypoint.celery.sh"]