name: Deploy Backend to Stage

on:
  push:
    branches:
      - ci/stage-deploy

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install black and flake8
        run: |
          pip install black flake8

      - name: Lint with black
        run: |
          black --check backend

      - name: Lint with flake8
        run: |
          flake8 backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/altiora-backend:stage

      - name: Upload docker-compose.stage.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.stage.yml"
          target: "/opt/backend"

      - name: Upload nginx config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "infra/nginx/altiora.conf"
          target: "/tmp"
          strip_components: 2

      - name: Docker login on server (non-interactive)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull and restart containers + reload nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/backend
            docker compose -f docker-compose.stage.yml pull
            docker compose -f docker-compose.stage.yml up -d --remove-orphans

            rm -f /etc/nginx/sites-enabled/altiora.conf
            mv /tmp/altiora.conf /etc/nginx/sites-available/altiora.conf
            ln -sf /etc/nginx/sites-available/altiora.conf /etc/nginx/sites-enabled/altiora.conf
            nginx -t && systemctl reload nginx
            