name: Style check

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - main
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set-up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependies
        run: |
          python -m pip install --upgrade pip
          pip install black==25.1.0
          pip install flake8==7.3.0

      - name: Test flake8
        run: python -m flake8 ./backend
      
      - name: Test black
        run: python -m black --check ./backend